<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitd37a11c1dd83a9fb8a5f5a754ea2eab7
{
    public static $prefixLengthsPsr4 = array (
        'P' =>
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' =>
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitd37a11c1dd83a9fb8a5f5a754ea2eab7::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitd37a11c1dd83a9fb8a5f5a754ea2eab7::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitd37a11c1dd83a9fb8a5f5a754ea2eab7::$classMap;

        }, null, ClassLoader::class);
    }
}
